import { ServiceBusClient, TokenProvider } from '@azure/service-bus';

// Client

export interface ServiceBusAadTokenCredentials {
  /**
   * Fully qualified domain name for ServiceBus.
   * Most likely, {yournamespace}.servicebus.windows.net
   */
  host: string;
  /**
   * The Token credentials generated by using the * `@azure/ms-rest-nodeauth` library.
   * It can be one of the following:
   *  - ApplicationTokenCredentials
   *  - UserTokenCredentials
   *  - DeviceTokenCredentials
   *  - MSITokenCredentials Token audience (or resource in case of MSI based credentials) to use when creating the credentials is https://servicebus.azure.net/
   */
  credentials: Parameters<typeof ServiceBusClient['createFromAadTokenCredentials']>[1];
}

export interface ServiceBusTokenProviderCredentials {
  host: string;
  tokenProvider: TokenProvider;
}

export interface ServiceBusConnectionStringCredentials {
  connectionString: string;
}

export type SbCredentials = ServiceBusAadTokenCredentials | ServiceBusTokenProviderCredentials | ServiceBusConnectionStringCredentials;

// Management

export interface ServiceBusManagementAadTokenCredentials extends ServiceBusAadTokenCredentials {
  resourceGroupName: string;
  namespace: string;
  subscriptionId: string;
}

export type SbManagementCredentials =
  | ServiceBusManagementAadTokenCredentials
  | ServiceBusConnectionStringCredentials;
